@host=https://localhost:7032

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJdWIiOiI0ZGM1NzViZS02NTFjLTQwZjMtOWNjZS1kN2Y3MmIwNTNmNWIiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiYWY2YTA4MDItNDJlYS00MTk3LTgxOTUtMTRjNzk4MWI0MDgyIiwiZXhwIjoxNjk2MTc5OTY0LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.HHiJ_k8ZhM6snvNnIFIzQhXPH-ZpLpV5Hyfn56Qntl0
